### ISSUE TITLE
Convert tests to use Ginkgo and Gomega.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dapper#35]
This can be done incrementally, rather than trying to port them all at once.

**Comment by danilvpetrov** [comment]
Technically there should not be much of the conversion as around 80% of the unit tests are using test function defined in `visitor_test,go` file. Once this function is converted, the remaining part should not be too hard.

**Comment by jmalloc** [comment]
I only used that function to get around the lack of assertions in the vanilla Go tests, so I'd rather get rid of that function altogether.

**Comment by danilvpetrov** [comment]
Fair enough.

**Comment by jmalloc** [comment]
We're moving away from these frameworks now.
