### ISSUE TITLE
Reconsider the way that map values are aligned.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dapper#4]
They are currently indented to align with the widest line of any map key, like so:

```
*engine.Engine{
    roles:  {
        {
            id:   17776544
            name: "messages.OpenAccount"
        }:                                               "command"
        {
            id:   17800064
            name: "messages.AccountCreditedForDeposit"
        }:                                               "event"
}
```

Note that I'm talking specifically about the alignment of the words `"command"` and `"event"` in this example.

I question the readability of this formatting, and further more it's probably *less* deterministic, since the values or presence/absence of other map keys affects how such keys are formatted. This is true even for single-line map keys.

I see a few options:
1. Don't align values if their key is multi-line -- this is still non-deterministic for single-line keys, but should improve readability overall
1. Don't align any values -- this is the most deterministic, but readability will be sacrificed in the simple case
1. Render keys and values on different lines -- this would remove all alignment, maintaining determinism, we'd have to come up with a readable way to disambiguate the keys/values.

**Comment by danilvpetrov** [comment]
Out of these three options which is the most preferable?

**Comment by jmalloc** [comment]
As discussed, I think (1) gives the best balance of readability and determinism.
