### ISSUE TITLE
Struct field alignment issue.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dapper#43]
```
*queue.Queue{
    DataStore:  *fixtures.DataStoreStub{
        DataStore:                *memory.dataStore{
            db:     {
                RWMutex: {
                    m:        <unlocked>
                    readers:  0
                    unlocked: 0xc0002d4f00 1/1
                    retry:    nil
                }
                open:    1
                events:  nil
                queue:   {
```

Notice the indent of `*memory.dataStore` on the third line. I'll have to work on a better reproduction for this, but just creating the issue before I forget.

**Comment by jmalloc** [comment]
I should have included the full output, I've lost it now.  This is aligning with some long field name down further, but I don't think it's supposed to do this when the value is multi-line.

**Comment by danilvpetrov** [comment]
I think I saw that kind of output before, it would be interesting to know is it doing so to align to the maximum width of the further output in `DataStore`? I will try to replicate it on my end as well.

**Comment by jmalloc** [comment]
It's this type `*fixtures.DataStoreStub` from Infix, there are definitely long field names in it.

**Comment by jmalloc** [comment]
There more I think on it, I'm not 100% sure this needs to be changed... it's probably done this way to try to keep the deterministic/stable output.

**Comment by jmalloc** [comment]
Just to put forward a kind of wacky idea, what if we were to render these indented struct & map keys with something between them to draw your eye to connect them:

```
*queue.Queue{
    DataStore .. *fixtures.DataStoreStub{
        DataStore ............... *memory.dataStore{
            db .... {
                RWMutex: {
                    m ......... <unlocked>
                    readers ... 0
                    unlocked .. 0xc0002d4f00 1/1
                    retry ..... nil
                }
                open .... 1
                events .. nil
                queue ... {
```

It still looks weird with the bottom of the struct cut-off like that... but an approach *something* like that would keep the determinism that we need (remember that Dapper was originally created to be diffable for `dogmatiq/testkit`) and make it a bit easier to read when there are structs with wide columns like that.

**Comment by jmalloc** [comment]
Closing as we haven't looked at it in 2 years, so it's likely not bothering us :)
